In [2]:
import pandas as pd
import numpy as np

In [3]:
df=pd.read_csv("spam.csv")
print(df.head())

  Category                                            Message
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...


In [4]:
df["Category"]

0        ham
1        ham
2       spam
3        ham
4        ham
        ... 
5567    spam
5568     ham
5569     ham
5570     ham
5571     ham
Name: Category, Length: 5572, dtype: object

In [5]:
df.Category.value_counts()

Category
ham     4825
spam     747
Name: count, dtype: int64

In [7]:
df["value of spam/ham"]=df['Category'].apply(lambda x:1 if x=="spam" else 0)
df

Category                                            Message  \
0         ham  Go until jurong point, crazy.. Available only ...   
1         ham                      Ok lar... Joking wif u oni...   
2        spam  Free entry in 2 a wkly comp to win FA Cup fina...   
3         ham  U dun say so early hor... U c already then say...   
4         ham  Nah I don't think he goes to usf, he lives aro...   
...       ...                                                ...   
5567     spam  This is the 2nd time we have tried 2 contact u...   
5568      ham               Will ü b going to esplanade fr home?   
5569      ham  Pity, * was in mood for that. So...any other s...   
5570      ham  The guy did some bitching but I acted like i'd...   
5571      ham                         Rofl. Its true to its name   

      value of spam/ham  
0                     0  
1                     0  
2                     1  
3                     0  
4                     0  
...                 ...  
5567                  1  
5568                  0  
5569                  0  
5570                  0  
5571                  0  

[5572 rows x 3 columns]

In [17]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(df.Message,df["value of spam/ham"],test_size=0.2)

In [37]:
x_train.shape

(4457,)

In [19]:
x_test.shape

(1115,)

In [20]:
type(x_train)

pandas.core.series.Series

In [56]:
print(x_train[:4])
print(x_train[:4][1063])

264     Hey I am really horny want to chat or see me n...
593     PRIVATE! Your 2003 Account Statement for 07753...
1063    Ok. Not sure what time tho as not sure if can ...
5305    Hi missed your Call and my mumHas beendropping...
Name: Message, dtype: object
Ok. Not sure what time tho as not sure if can get to library before class. Will try. See you at some point! Have good eve.


In [23]:
print(type(y_train))

<class 'pandas.core.series.Series'>


In [24]:
print(y_train[:4])

264     1
593     1
1063    0
5305    0
Name: value of spam/ham, dtype: int64


In [25]:
from sklearn.feature_extraction.text import CountVectorizer
v=CountVectorizer()
x_train_cv=v.fit_transform(x_train.values)
x_train_cv

<Compressed Sparse Row sparse matrix of dtype 'int64'
	with 59041 stored elements and shape (4457, 7771)>

In [26]:
print(type(x_train.values))

<class 'numpy.ndarray'>


In [28]:
x_train_cv.toarray()[:2]

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], shape=(2, 7771))

In [29]:
x_train_cv.shape

(4457, 7771)

In [30]:
v.get_feature_names_out()

array(['00', '000', '008704050406', ..., 'zouk', 'zyada', 'èn'],
      shape=(7771,), dtype=object)

In [31]:
v.get_feature_names_out().shape

(7771,)

In [32]:
dir(v)

['_CountVectorizer__metadata_request__fit',
 '_CountVectorizer__metadata_request__transform',
 '__annotations__',
 '__class__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__firstlineno__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__setstate__',
 '__sizeof__',
 '__sklearn_clone__',
 '__sklearn_tags__',
 '__static_attributes__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 '_build_request_for_signature',
 '_char_ngrams',
 '_char_wb_ngrams',
 '_check_stop_words_consistency',
 '_check_vocabulary',
 '_count_vocab',
 '_doc_link_module',
 '_doc_link_template',
 '_doc_link_url_param_generator',
 '_get_default_requests',
 '_get_doc_link',
 '_get_metadata_request',
 '_get_param_names',
 '_get_params_html',
 '_html_repr',
 '_limit_features',
 '_parameter_constraints'

In [33]:
v.vocabulary_

{'hey': 3444,
 'am': 925,
 'really': 5621,
 'horny': 3521,
 'want': 7410,
 'to': 6953,
 'chat': 1748,
 'or': 4995,
 'see': 5995,
 'me': 4428,
 'naked': 4702,
 'text': 6803,
 'hot': 3530,
 '69698': 580,
 'charged': 1737,
 'at': 1113,
 '150pm': 302,
 'unsubscribe': 7205,
 'stop': 6508,
 'private': 5435,
 'your': 7739,
 '2003': 341,
 'account': 773,
 'statement': 6467,
 'for': 2950,
 '07753741225': 31,
 'shows': 6149,
 '800': 626,
 'un': 7153,
 'redeemed': 5660,
 'points': 5300,
 'call': 1601,
 '08715203677': 125,
 'identifier': 3620,
 'code': 1888,
 '42478': 478,
 'expires': 2729,
 '24': 356,
 '10': 252,
 '04': 15,
 'ok': 4939,
 'not': 4848,
 'sure': 6645,
 'what': 7504,
 'time': 6921,
 'tho': 6879,
 'as': 1079,
 'if': 3627,
 'can': 1626,
 'get': 3132,
 'library': 4124,
 'before': 1289,
 'class': 1837,
 'will': 7548,
 'try': 7085,
 'you': 7736,
 'some': 6313,
 'point': 5299,
 'have': 3375,
 'good': 3201,
 'eve': 2663,
 'hi': 3447,
 'missed': 4530,
 'and': 954,
 'my': 4683,
 'mumhas': 466

In [34]:
v.get_feature_names_out()[4364]

'maneesha'

In [35]:
x_train_cv_arr=x_train_cv.toarray()

In [36]:
x_train_cv_arr

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], shape=(4457, 7771))

In [64]:
a=np.where(x_train_cv_arr[0]!=0)
print(a)

(array([ 302,  580,  925, 1113, 1737, 1748, 3444, 3521, 3530, 4428, 4702,
       4995, 5621, 5995, 6508, 6803, 6953, 7205, 7410]),)


In [65]:
list_of_first_email=[ 302,  925, 1113, 1737, 1748, 3444, 3521, 3530, 4428, 4702, 4995,5621, 5995, 6508, 7205, 7410]
for i in list_of_first_email:
    print(v.get_feature_names_out()[i],x_train_cv_arr[0][i])

150pm 1
am 1
at 1
charged 1
chat 1
hey 1
horny 1
hot 1
me 1
naked 1
or 1
really 1
see 1
stop 1
unsubscribe 1
want 1


In [66]:
from sklearn.naive_bayes import MultinomialNB

In [67]:
model=MultinomialNB()
model.fit(x_train_cv,y_train)

MultinomialNB()

In [68]:
x_test_cv=v.transform(x_test)

In [69]:
from sklearn.metrics import classification_report

In [70]:
y_pred=model.predict(x_text_cv)
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.98      1.00      0.99       944
           1       0.98      0.91      0.95       171

    accuracy                           0.98      1115
   macro avg       0.98      0.95      0.97      1115
weighted avg       0.98      0.98      0.98      1115



In [71]:
emails = [
    'Hey mohan, can we get together to watch footbal game tomorrow?',
    'Upto 20% discount on parking, exclusive offer just for you. Dont miss this reward!'
]

emails_count = v.transform(emails)
model.predict(emails_count)

array([0, 1])